# Site settings
title: Yaseen Majeed
email: yaseenmajeed5@hotmail.com
url: https://yaseenmajeed.github.io
description: "I talk about Football and Programming."

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Yaseen Majeed
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/khalidyaseen1
  - title: facebook
    url: https://www.facebook.com/khalid.yasee
  - title: github
    url: https://github.com/khalidyaseen

# Postal address (add as many lines as necessary)
address:
  - line: Srinagar
  - line: Kashmir, J&K 190001

# Credits content
credits: 'Some friends :)'

# Build settings
markdown: kramdown
permalink: pretty
